language: generic
sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - COLLECT_ERROR= 1

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t razear/inventory-web-app-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true razear/inventory-web-app-dev npm test

after_success:
  - docker build  --build-arg BACKEND_API=http://localhost:3050/api --build-arg WEBSOCKET_API=ws://localhost:3050/api -t razear/mega-electric-web-app-dev:latest -t razear/mega-electric-web-app:$SHA -f Dockerfile .
  - docker push razear/mega-electric-web-app-dev:$SHA
  - docker push razear/mega-electric-web-app-dev:latest
before_deploy:
  - docker build  --build-arg BACKEND_API=$BACKEND_API --build-arg WEBSOCKET_API=$WEBSOCKET_API -t razear/mega-electric-web-app:latest -t razear/mega-electric-web-app:$SHA -f Dockerfile .
  - docker push razear/mega-electric-web-app:$SHA
  - docker push razear/mega-electric-web-app:latest
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
after_deploy:
  - echo "y" | fandogh service reset --service mege-electric-nginx