language: generic
sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t razear/inventory-web-app -f Dockerfile.dev .

script:
  - docker run -e CI=true razear/inventory-web-app npm test

after_success:
  - pip install fandogh-cli --updagrade
  - fandogh login --username $FANDOGH_USERNAME --password $FANDOGH_PASSWORD
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main