language: generic
sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - COLLECT_ERROR= 1

before_install:
  - pip install fandogh-cli --upgrade
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t razear/inventory-web-app-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true razear/inventory-web-app-dev npm test

after_success:
  - fandogh login --username $FANDOGH_USERNAME --password $FANDOGH_PASSWORD
  - fandogh namespace active --name $FANDOGH_NAMESPACE
before_deploy:
  - docker build  --build-arg BACKEND_API=$BACKEND_API -t razear/mega-electric-web-app:latest -t razear/mega-electric-web-app:$SHA -f Dockerfile .
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main