language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t razear/inventory-web-app -f Dockerfile.dev .

script:
  - docker run -e CI=true razear/inventory-web-app npm test
