kind: ExternalService
name: mega-electric-web-app
spec:
  image:  razear/mega-electric-web-app:${SHA}
  env:
    - name: REACT_APP_HOST
      #      value: ${SPRING_PROFILES_ACTIVE}
      secret: backend-api

  port_mapping:
    - port: 3000
      target_port: 3000
      # default protocol is TCP
  resources:
    memory: 200Mi