//////////////////////////////////////////////////////////////////////////////
export const SHOW_SUCCESS_MESSAGE = {
    LOAD: 'SHOW SUCCESS MESSAGE LOAD',
    SUCCESS: 'SHOW SUCCESS MESSAGE SUCCESS',
    FAILED: 'SHOW SUCCESS MESSAGE FAILED'
}
export const SHOW_ERROR_MESSAGE = {
    LOAD: 'SHOW ERROR MESSAGE LOAD',
    SUCCESS: 'SHOW ERROR MESSAGE SUCCESS',
    FAILED: 'SHOW ERROR MESSAGE FAILED'
}

export const LOADING = {
    START: 'LOADING START',
    STOP: 'LOADING STOP',
}

//////////////////////////////////////////////////////////////////////////////AUTH
export const LOGIN = {
    LOAD: 'LOGIN LOAD',
    SUCCESS: 'LOGIN SUCCESS',
    FAILED: 'LOGIN FAILED'
}
export const LOGOUT = {
    LOAD: 'LOGOUT LOAD',
    SUCCESS: 'LOGOUT SUCCESS',
    FAILED: 'LOGOUT FAILED'
}




//////////////////////////////////////////////////////////////////////////////Customer
export const GET_CUSTOMER_PAGE = {
    LOAD: 'GET CUSTOMER PAGE LOAD',
    SUCCESS: 'GET CUSTOMER PAGE SUCCESS',
    FAILED: 'GET CUSTOMER PAGE FAILED'
}
export const GET_CUSTOMER_LIST = {
    LOAD: 'GET CUSTOMER LIST LOAD',
    SUCCESS: 'GET CUSTOMER LIST SUCCESS',
    FAILED: 'GET CUSTOMER LIST FAILED'
}
export const GET_CUSTOMER = {
    LOAD: 'GET CUSTOMER LOAD',
    SUCCESS: 'GET CUSTOMER SUCCESS',
    FAILED: 'GET CUSTOMER FAILED'
}
export const SAVE_CUSTOMER = {
    LOAD: 'SAVE CUSTOMER LOAD',
    SUCCESS: 'SAVE CUSTOMER SUCCESS',
    FAILED: 'SAVE CUSTOMER FAILED'
}
export const UPDATE_CUSTOMER = {
    LOAD: 'UPDATE CUSTOMER LOAD',
    SUCCESS: 'UPDATE CUSTOMER SUCCESS',
    FAILED: 'UPDATE CUSTOMER FAILED'
}
export const DELETE_CUSTOMER = {
    LOAD: 'DELETE CUSTOMER LOAD',
    SUCCESS: 'DELETE CUSTOMER SUCCESS',
    FAILED: 'DELETE CUSTOMER FAILED'
}
//////////////////////////////////////////////////////////////////////////////Supplier
export const GET_SUPPLIER_PAGE = {
    LOAD: 'GET SUPPLIER PAGE LOAD',
    SUCCESS: 'GET SUPPLIER PAGE SUCCESS',
    FAILED: 'GET SUPPLIER PAGE FAILED'
}
export const GET_SUPPLIER_LIST = {
    LOAD: 'GET SUPPLIER LIST LOAD',
    SUCCESS: 'GET SUPPLIER LIST SUCCESS',
    FAILED: 'GET SUPPLIER LIST FAILED'
}
export const GET_SUPPLIER = {
    LOAD: 'GET SUPPLIER LOAD',
    SUCCESS: 'GET SUPPLIER SUCCESS',
    FAILED: 'GET SUPPLIER FAILED'
}
export const SAVE_SUPPLIER = {
    LOAD: 'SAVE SUPPLIER LOAD',
    SUCCESS: 'SAVE SUPPLIER SUCCESS',
    FAILED: 'SAVE SUPPLIER FAILED'
}
export const UPDATE_SUPPLIER = {
    LOAD: 'UPDATE SUPPLIER LOAD',
    SUCCESS: 'UPDATE SUPPLIER SUCCESS',
    FAILED: 'UPDATE SUPPLIER FAILED'
}
export const DELETE_SUPPLIER = {
    LOAD: 'DELETE SUPPLIER LOAD',
    SUCCESS: 'DELETE SUPPLIER SUCCESS',
    FAILED: 'DELETE SUPPLIER FAILED'
}

//////////////////////////////////////////////////////////////////////////////Purchase Invoice
export const GET_PURCHASE_INVOICE_LIST = {
    LOAD: 'GET PURCHASE INVOICE LIST LOAD',
    SUCCESS: 'GET PURCHASE INVOICE LIST SUCCESS',
    FAILED: 'GET PURCHASE INVOICE LIST FAILED'
}

export const GET_PURCHASE_INVOICE = {
    LOAD: 'GET PURCHASE INVOICE LOAD',
    SUCCESS: 'GET PURCHASE INVOICE SUCCESS',
    FAILED: 'GET PURCHASE INVOICE FAILED'
}

export const SAVE_PURCHASE_INVOICE = {
    LOAD: 'SAVE PURCHASE INVOICE LOAD',
    SUCCESS: 'SAVE PURCHASE INVOICE SUCCESS',
    FAILED: 'SAVE PURCHASE INVOICE FAILED'
}

export const DELETE_PURCHASE_INVOICE = {
    LOAD: 'DELETE PURCHASE INVOICE LOAD',
    SUCCESS: 'DELETE PURCHASE INVOICE SUCCESS',
    FAILED: 'DELETE PURCHASE INVOICE FAILED'
}
//////////////////////////////////////////////////////////////////////////////Sale Invoice


export const GET_SALE_INVOICE_LIST = {
    LOAD: 'GET SALE INVOICE LIST LOAD',
    SUCCESS: 'GET SALE INVOICE LIST SUCCESS',
    FAILED: 'GET SALE INVOICE LIST FAILED'
}
export const GET_SALE_INVOICE = {
    LOAD: 'GET SALE INVOICE LOAD',
    SUCCESS: 'GET SALE INVOICE SUCCESS',
    FAILED: 'GET SALE INVOICE FAILED'
}
export const SAVE_SALE_INVOICE = {
    LOAD: 'SAVE SALE INVOICE LOAD',
    SUCCESS: 'SAVE SALE INVOICE SUCCESS',
    FAILED: 'SAVE SALE INVOICE FAILED'
}

export const DELETE_SALE_INVOICE = {
    LOAD: 'DELETE SALE INVOICE LOAD',
    SUCCESS: 'DELETE SALE INVOICE SUCCESS',
    FAILED: 'DELETE SALE INVOICE FAILED'
}

//////////////////////////////////////////////////////////////////////////////Product

export const GET_PRODUCT_PAGE = {
    LOAD: 'GET PRODUCT PAGE LOAD',
    SUCCESS: 'GET PRODUCT PAGE SUCCESS',
    FAILED: 'GET PRODUCT PAGE FAILED'
}
export const GET_PRODUCT_LIST = {
    LOAD: 'GET PRODUCT LIST LOAD',
    SUCCESS: 'GET PRODUCT LIST SUCCESS',
    FAILED: 'GET PRODUCT LIST FAILED'
}
export const GET_PRODUCT = {
    LOAD: 'GET PRODUCT LOAD',
    SUCCESS: 'GET PRODUCT SUCCESS',
    FAILED: 'GET PRODUCT FAILED'
}
export const SAVE_PRODUCT = {
    LOAD: 'SAVE PRODUCT LOAD',
    SUCCESS: 'SAVE PRODUCT SUCCESS',
    FAILED: 'SAVE PRODUCT FAILED'
}
export const UPDATE_PRODUCT = {
    LOAD: 'UPDATE PRODUCT LOAD',
    SUCCESS: 'UPDATE PRODUCT SUCCESS',
    FAILED: 'UPDATE PRODUCT FAILED'
}
export const DELETE_PRODUCT = {
    LOAD: 'DELETE PRODUCT LOAD',
    SUCCESS: 'DELETE PRODUCT SUCCESS',
    FAILED: 'DELETE PRODUCT FAILED'
}


//////////////////////////////////////////////////////////////////////////////Invoice
export const GET_INVOICE_PAGE = {
    LOAD: 'GET INVOICE PAGE LOAD',
    SUCCESS: 'GET INVOICE PAGE SUCCESS',
    FAILED: 'GET INVOICE PAGE FAILED'
}

//////////////////////////////////////////////////////////////////////////////TRANSACTION
export const GET_TRANSACTION_PAGE = {
    LOAD: 'GET TRANSACTION PAGE LOAD',
    SUCCESS: 'GET TRANSACTION PAGE SUCCESS',
    FAILED: 'GET TRANSACTION PAGE FAILED'
}
//////////////////////////////////////////////////////////////////////////////PROFILE
export const GET_USER_PROFILE = {
    LOAD: 'GET USER PROFILE LOAD',
    SUCCESS: 'GET USER PROFILE SUCCESS',
    FAILED: 'GET USER PROFILE FAILED'
}
export const UPDATE_USER_PROFILE = {
    LOAD: 'UPDATE USER PROFILE LOAD',
    SUCCESS: 'UPDATE USER PROFILE SUCCESS',
    FAILED: 'UPDATE USER PROFILE FAILED'
}
