export const GET_PURCHASE_INVOICE_LIST = {
    LOAD: 'GET PURCHASE INVOICE LIST LOAD',
    SUCCESS: 'GET PURCHASE INVOICE LIST SUCCESS',
    FAILED: 'GET PURCHASE INVOICE LIST FAILED'
}

export const GET_PURCHASE_INVOICE = {
    LOAD: 'GET PURCHASE INVOICE LOAD',
    SUCCESS: 'GET PURCHASE INVOICE SUCCESS',
    FAILED: 'GET PURCHASE INVOICE FAILED'
}

export const SAVE_PURCHASE_INVOICE = {
    LOAD: 'SAVE PURCHASE INVOICE LOAD',
    SUCCESS: 'SAVE PURCHASE INVOICE SUCCESS',
    FAILED: 'SAVE PURCHASE INVOICE FAILED'
}

export const DELETE_PURCHASE_INVOICE = {
    LOAD: 'DELETE PURCHASE INVOICE LOAD',
    SUCCESS: 'DELETE PURCHASE INVOICE SUCCESS',
    FAILED: 'DELETE PURCHASE INVOICE FAILED'
}

