//////////////////////////////////////////////////////////////////////////////Customer
export const GET_CUSTOMER_PAGE = {
    LOAD: 'GET CUSTOMER PAGE LOAD',
    SUCCESS: 'GET CUSTOMER PAGE SUCCESS',
    FAILED: 'GET CUSTOMER PAGE FAILED'
}
export const GET_CUSTOMER_LIST = {
    LOAD: 'GET CUSTOMER LIST LOAD',
    SUCCESS: 'GET CUSTOMER LIST SUCCESS',
    FAILED: 'GET CUSTOMER LIST FAILED'
}
export const GET_CUSTOMER = {
    LOAD: 'GET CUSTOMER LOAD',
    SUCCESS: 'GET CUSTOMER SUCCESS',
    FAILED: 'GET CUSTOMER FAILED'
}
export const SAVE_CUSTOMER = {
    LOAD: 'SAVE CUSTOMER LOAD',
    SUCCESS: 'SAVE CUSTOMER SUCCESS',
    FAILED: 'SAVE CUSTOMER FAILED'
}
export const UPDATE_CUSTOMER = {
    LOAD: 'UPDATE CUSTOMER LOAD',
    SUCCESS: 'UPDATE CUSTOMER SUCCESS',
    FAILED: 'UPDATE CUSTOMER FAILED'
}
export const DELETE_CUSTOMER = {
    LOAD: 'DELETE CUSTOMER LOAD',
    SUCCESS: 'DELETE CUSTOMER SUCCESS',
    FAILED: 'DELETE CUSTOMER FAILED'
}
//////////////////////////////////////////////////////////////////////////////Supplier
export const GET_SUPPLIER_PAGE = {
    LOAD: 'GET SUPPLIER PAGE LOAD',
    SUCCESS: 'GET SUPPLIER PAGE SUCCESS',
    FAILED: 'GET SUPPLIER PAGE FAILED'
}
export const GET_SUPPLIER_LIST = {
    LOAD: 'GET SUPPLIER LIST LOAD',
    SUCCESS: 'GET SUPPLIER LIST SUCCESS',
    FAILED: 'GET SUPPLIER LIST FAILED'
}
export const GET_SUPPLIER = {
    LOAD: 'GET SUPPLIER LOAD',
    SUCCESS: 'GET SUPPLIER SUCCESS',
    FAILED: 'GET SUPPLIER FAILED'
}
export const SAVE_SUPPLIER = {
    LOAD: 'SAVE SUPPLIER LOAD',
    SUCCESS: 'SAVE SUPPLIER SUCCESS',
    FAILED: 'SAVE SUPPLIER FAILED'
}
export const UPDATE_SUPPLIER = {
    LOAD: 'UPDATE SUPPLIER LOAD',
    SUCCESS: 'UPDATE SUPPLIER SUCCESS',
    FAILED: 'UPDATE SUPPLIER FAILED'
}
export const DELETE_SUPPLIER = {
    LOAD: 'DELETE SUPPLIER LOAD',
    SUCCESS: 'DELETE SUPPLIER SUCCESS',
    FAILED: 'DELETE SUPPLIER FAILED'
}

//////////////////////////////////////////////////////////////////////////////Purchase Invoice
export const GET_PURCHASE_INVOICE_LIST = {
    LOAD: 'GET PURCHASE INVOICE LIST LOAD',
    SUCCESS: 'GET PURCHASE INVOICE LIST SUCCESS',
    FAILED: 'GET PURCHASE INVOICE LIST FAILED'
}

export const GET_PURCHASE_INVOICE = {
    LOAD: 'GET PURCHASE INVOICE LOAD',
    SUCCESS: 'GET PURCHASE INVOICE SUCCESS',
    FAILED: 'GET PURCHASE INVOICE FAILED'
}

export const SAVE_PURCHASE_INVOICE = {
    LOAD: 'SAVE PURCHASE INVOICE LOAD',
    SUCCESS: 'SAVE PURCHASE INVOICE SUCCESS',
    FAILED: 'SAVE PURCHASE INVOICE FAILED'
}

export const DELETE_PURCHASE_INVOICE = {
    LOAD: 'DELETE PURCHASE INVOICE LOAD',
    SUCCESS: 'DELETE PURCHASE INVOICE SUCCESS',
    FAILED: 'DELETE PURCHASE INVOICE FAILED'
}
//////////////////////////////////////////////////////////////////////////////Sale Invoice


export const GET_SALE_INVOICE_LIST = {
    LOAD: 'GET SALE INVOICE LIST LOAD',
    SUCCESS: 'GET SALE INVOICE LIST SUCCESS',
    FAILED: 'GET SALE INVOICE LIST FAILED'
}
export const GET_SALE_INVOICE = {
    LOAD: 'GET SALE INVOICE LOAD',
    SUCCESS: 'GET SALE INVOICE SUCCESS',
    FAILED: 'GET SALE INVOICE FAILED'
}
export const SAVE_SALE_INVOICE = {
    LOAD: 'SAVE SALE INVOICE LOAD',
    SUCCESS: 'SAVE SALE INVOICE SUCCESS',
    FAILED: 'SAVE SALE INVOICE FAILED'
}

export const DELETE_SALE_INVOICE = {
    LOAD: 'DELETE SALE INVOICE LOAD',
    SUCCESS: 'DELETE SALE INVOICE SUCCESS',
    FAILED: 'DELETE SALE INVOICE FAILED'
}


